### ISSUE TITLE
Is there a lite mode to make google maps perform faster on mobile?

### ISSUE THREAD

**Issue by TheInvoker** [jbdemonte/gmap3#101]
Google officially has a lite mode for its maps

https://support.google.com/maps/answer/3031966?hl=en

Is there a setting I can enable for this gmaps3, so that it would perform and run faster on mobile? I have a fast phone (note 4), but it still seems to lag a little when panning around.

**Comment by jbdemonte** [comment]
update to 7.1 & http://gmap3.net/configuration.html

**Comment by TheInvoker** [comment]
@jbdemonte  I can get 7.1, but how do I enable lite on it? I don't understand.
