### ISSUE TITLE
Streetview GREY

### ISSUE THREAD

**Issue by comtronix** [jbdemonte/gmap3#105]
when i load Gmap in a div, the streetview is GREY. the map is OK.
`function drawGmapsView( addressInfo ){
    $.get( "http://maps.googleapis.com/maps/api/geocode/json", { sensor: false, address: addressInfo }, function( response ){
        var location = response.results[0];
           
        var gMapsSettings ={
            el: '#map-container',
            lat : location.geometry.location.lat,
            lng : location.geometry.location.lng
        };
        new GMaps.createPanorama( gMapsSettings );
        $("#map-container").show();
    })
} `

**Comment by jbdemonte** [comment]
You're not targetting the good library, regarding your code, you use https://hpneo.github.io/gmaps/examples/streetview.html
