### ISSUE TITLE
Google Maps API error: MissingKeyMapError

### ISSUE THREAD

**Issue by ozzytr** [jbdemonte/gmap3#107]
please fix it this problem.

source: http://stackoverflow.com/questions/37991340/error-google-maps-api-error-missingkeymaperror/37991723

**Comment by MrShabir** [comment]
Now i think we must need to add Google API Key for this.
http://googlegeodevelopers.blogspot.co.uk/2016/06/building-for-scale-updates-to-google.html
But still waiting for a reply from ( jbdemonte).
Thanks

**Comment by ozzytr** [comment]
I added a api key and solved problem.

<script src="http://maps.google.com/maps/api/js?&key=XXXXX&sensor=false"></script>

thx.

**Comment by SetarehSalehee** [comment]
Hi,
Thank you for the update.  I read about this issue and I found out that there is a 25,000 page loads limitation per each API key. Since yours is a famous plugin and I am sure it has a lot of users, how did you handle this. I mean if I am a developer with  2500 clients who receive 100 page views per day, It means that your plugin won't show google map to any other one? 
Thank you for answering back...

**Comment by MrShabir** [comment]
I think best way is this, Don't use your API Key for Clients, Use Client Account API for his project then this problem can be solved.

**Comment by SetarehSalehee** [comment]
@MrShabir : You totally are right, this is what I did by far, but I am a theme developer with lots of clients, each of them has  a seperated website, for me it means that I have to make them each get their own client ID and trust me for some of them this can be very hard and frustrating. 
Using an API key with this limitation will make their maps not to show(probably). I am more of looking for something permanent. I am using iFrame insertion to avoid this but this means that I will lose custom styling of this plugin, any ideas on how I can have map and styling without using the API key?
Thank you

**Comment by jbdemonte** [comment]
To add the API key, follow this example https://github.com/jbdemonte/gmap3/blob/master/dist/examples/config.html

**Comment by rajkumarexe** [comment]
@jbdemonte can we use the API key u mentioned in the above link for our projects or we have to get our own APi key

**Comment by jbdemonte** [comment]
You have to use your own API key
