### ISSUE TITLE
Can not clear the map before drawing a route

### ISSUE THREAD

**Issue by aneroin** [jbdemonte/gmap3#110]
i have this part of code:

```
function calculate(){

var from = $("#from").val();
var to = $("#to").val();
var totalDistance = 0;

$('#map')
	.gmap3({
		address: from,
		zoom: 6,
		mapTypeId : google.maps.MapTypeId.ROADMAP
	})
	.route({
		origin:from,
		destination:to,
		travelMode: google.maps.DirectionsTravelMode.DRIVING
	})
	.directionsrenderer(function (results) {
		if (results) {
			console.log(results);
			if (results.status == "OK"){
				var legs = results.routes[0].legs;
				for(var i=0; i<legs.length; i++){
					totalDistance += (legs[i].distance.value / 1000);
				}
			} else {
				console.log(results.status);
			}
			console.log(totalDistance);
			$('#dist').text(totalDistance);
			return {
				panel: "#box",
				directions: results
			}
		}
	});
}
```

It draws a route on the map and calculates total distance by it's legs.
It works ok until i draw another one route with this function.
When i draw every next route, previous ones are still there. 

I need to remove previous route each time before drawing new one, but unfortunately I can not figure out how to do this. Any suggestions, please?

Version of gmap3 is 7.0.0 from https://cdn.jsdelivr.net/gmap3/7.0.0/gmap3.min.js
and yes, I already read all available documentation for API.

**Comment by cruger2002** [comment]
I'm deleting map, and insert new one. 
`  $('#gmap').empty();
    var newmap = $('<div></div>');
    $('#gmap').append(newmap)`

newmap is gmap3 object

**Comment by jbdemonte** [comment]
Here is a solution


      function calculate(){
    
        var from = $("#from").val();
        var to = $("#to").val();
        var totalDistance = 0;
    
        if (calculate.previous) {
          calculate.previous.setMap(null);
        }
    
        $('#map')
                .gmap3({
                  address: from,
                  zoom: 6,
                  mapTypeId : google.maps.MapTypeId.ROADMAP
                })
                .route({
                  origin:from,
                  destination:to,
                  travelMode: google.maps.DirectionsTravelMode.DRIVING
                })
                .directionsrenderer(function (results) {
                  if (results) {
                    console.log(results);
                    if (results.status == "OK"){
                      var legs = results.routes[0].legs;
                      for(var i=0; i<legs.length; i++){
                        totalDistance += (legs[i].distance.value / 1000);
                      }
                    } else {
                      console.log(results.status);
                    }
                    console.log(totalDistance);
                    $('#dist').text(totalDistance);
                    return {
                      panel: "#box",
                      directions: results
                    }
                  }
                })
                .then(function (dr) {
                  calculate.previous = dr;
                })
      }
