### ISSUE TITLE
replace dress by gps coordinates

### ISSUE THREAD

**Issue by kodjoe** [jbdemonte/gmap3#112]
Hello I have this part of code for my gmap3 and I would like to 
1. Replace my adress by gps coordinates
2. Put my marker at center when I resize my page.

      
      $(function(){
        $('#adresse').gmap3(
          {marker:{address: " Apple CAP 3000 Avenue Eugène Donadeï, 06700 Saint-Laurent Du Var, France"},
            map:{options:{zoom: 17}
            }
          });
      });

Thank you

**Comment by jbdemonte** [comment]
use an array as position instead of the address (http://gmap3.net/api-marker.html)

**Comment by kodjoe** [comment]
thank you sir ;D
