### ISSUE TITLE
how to add muptiple markers with different info windows?

### ISSUE THREAD

**Issue by weilinzung** [jbdemonte/gmap3#113]
how to add muptiple markers with different info windows &  custom map style?

thanks!

**Comment by cruger2002** [comment]
I made it like some code below

`    $('#gmap').gmap3({
      address:'Poland',
      zoom: 12
    })
    .marker(locations)
    .infowindow(locations)
    .then(function (infowindow) {
      var map = this.get(0);
      var marker = this.get(1);
      marker.forEach(function(item,i){
        item.addListener('click', function() {
          infowindow[i].open(map, item);
        });
      })
    }).fit();`

locations is a json object like 
[{address:'street bla bla',content:'name of ponint'},... ]

**Comment by lolotoobo** [comment]
Thanx cruger2002 for this solution, but now the problem is how to close the opened infowindow if we click on another marker ?
