### ISSUE TITLE
Places API

### ISSUE THREAD

**Issue by ziga-miklic** [jbdemonte/gmap3#116]
Hello,

are there any plans on adding an option for the [Places API](https://developers.google.com/places/) next to the [Geocoding API](https://developers.google.com/maps/documentation/geocoding/start)?

Searching by name (eg. "Howard University") was working until recently, but now it only works using the address (eg. "405 Howard Pl NW, Washington").

We also see a similar question asked on the forum: http://forum.gmap3.net/viewtopic.php?id=1417

Source of Google's blog post on this topic (where they recommend using the Places API): https://googlegeodevelopers.blogspot.si/2016/11/address-geocoding-in-google-maps-apis.html

Thank you for your answer and for all your work on Gmap.

Kind regards,
Ziga Miklic

**Comment by jbdemonte** [comment]
Hi,
Honestly, I'm currently really over-buzzy at work, so, I don't think I'll be able to have a look on this before a while

**Comment by ziga-miklic** [comment]
No problem. If I submit a pull request would you be willing to take a look / consider using it? If so, please give me your preference / suggestion on how to allow switching between APIs. Eg. would the `apiType: 'geocoding' / 'places'` be ok? Thank you again.

**Comment by jbdemonte** [comment]
Yes sure, I'll be pleased to have a look on it, we can continue by email if you don't mind

**Comment by ziga-miklic** [comment]
Great! I will email you in the next few days with the changed code.
