### ISSUE TITLE
How to trigger/open infowindow from outside the map

### ISSUE THREAD

**Issue by lnunesbr** [jbdemonte/gmap3#117]
It's not very clear how to trigger events from outside the map, let's say I have same items i previously added to gmap3 cluster markers, like shown at: (https://github.com/jbdemonte/gmap3/blob/master/dist/examples/cluster.html) as regular links.

It could have something like:

```
<a href='#' data-marker-latlng='36.1128,-113.9961'>Location 1</a>
<a href='#' data-marker-latlng='44.4280,-110.5885'>Location 2</a>
etc...
```

I'd need to click in the location link outside of the map, and open the respective infowindow inside the map.

I am using gmap3 v7, and i'm kind of stuck to make it work. I have found some old stuff in google, but all pointing to old versions of gmap.

**Comment by naszybko** [comment]
Hi
Had the same issue, this is what I came up with:

Imagine you have created gmap3 with multiple markers from links.
```
<div id="maplinks">
<a href='#' data-lat='36.1128' data-lon='-113.9961' data-markerid="1">Location 1</a>
<a href='#' data-lat='44.4280' data-lon='-110.5885' data-markerid="2">Location 2</a>
</div>
```

At first, you create gmap3:
```
var markers = new Array();
            $('#maplinks a').each(function () {
                var htmltxt = $(this).html();
                var mark = {

                position: new Array($(this).data('lat'), $(this).data('lon')),
                id: $(this).data('id'),
                data: htmltxt,
                tag: 'marker'};
                markers.push(mark);
            });
            $("#map")
                    .gmap3()
                    .marker(markers).fit()
                    .infowindow({content: ""})
                    .then(function (infowindow) {
                        var map = this.get(0);
                        var marker = this.get(1);
                        $(marker).each(function () {
                            this.addListener('click', function () {
                                infowindow.setContent(this.data);
                                infowindow.open(map, this);
                            });
                        });
                    });
```

Then you just add click event for your links.
```
$("#maplinks a").click(function(event){
event.preventDefault();
            var markerid = $(event.target).data("markerid");
            var marker = $("#map").gmap3()
                    .then(function (marker) {
                        var markers = (this.get(1));
                        $(markers).each(function () {
                            if (this.id == markerid) {
                                //here is your clicked marker
                                google.maps.event.trigger(this, 'click', {});
                            }
                        });
                    });
});
```

**Comment by lnunesbr** [comment]
Hi @naszybko this is **very** useful, it works pretty well. Thanks a lot.

Perhaps, this don't seems to work with clusters. In the click event, when the markers are loaded with `var markers = (this.get(1));` this returns undefined.

There is the complicating factor the markers would become available only after zooming in.

I used the following cluster structure: https://github.com/jbdemonte/gmap3/issues/108#issuecomment-257142154

If you have any thoughts.

**Comment by lnunesbr** [comment]
I got it...

@naszybko thanks for you collaboration. That opened my mind, definitelly, couldn't figure it out without that.

In case anyone is interested, test code is:

```
<html>    
  <head> 
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <link type="text/css" rel="stylesheet" href="style.css" />
    <script type="text/javascript" src="../gmap3.js"></script>
  <body>
<div id="map2" class="gmap3"></div>
<script>
  $(function () {
            var cluster, gmap;


          // create an array of markers
          var mymarkers = new Array();
            $('#maplinks a').each(function () {
                var htmltxt = $(this).html();
                var newmarker = {
                position: new Array($(this).data('lat'), $(this).data('lon')),
                id: $(this).data('markerid'),
                data: htmltxt,
                tag: 'marker'};
                mymarkers.push(newmarker);
            });
            
            // create gmap3:
            $("#map2")
                    .gmap3({center: [36.1128,-113.9961], zoom: 4})
                    .then(function (_gmap) {
                          gmap = _gmap;
                      })
                    .infowindow({
                      content: ''
                    })
                    .then(function (iw) {
                      infowindow = iw;
                    })
                    .cluster({
                        size: 200,
                        markers: mymarkers,
                        cb: function (markers) {
                            if (markers.length > 1) { // 1 marker stay unchanged (because cb returns nothing)
                                if (markers.length < 20) {
                                    return {
                                        content: "<div class='cluster cluster-1'>" + markers.length + "</div>",
                                        x: -26,
                                        y: -26
                                    };
                                }
                                if (markers.length < 50) {
                                    return {
                                        content: "<div class='cluster cluster-2'>" + markers.length + "</div>",
                                        x: -26,
                                        y: -26
                                    };
                                }
                                return {
                                    content: "<div class='cluster cluster-3'>" + markers.length + "</div>",
                                    x: -33,
                                    y: -33
                                };
                            }
                        }
                    }).then(function (_cluster) {
                          cluster = _cluster;
                      })
                    .on('click', function (marker, clusterOverlay, cluster, event) {
                      if (marker) {
                        infowindow.setContent(marker.data);
                        infowindow.open(marker.getMap(), marker);
                      }
                      console.warn(marker);
                    })
        
                    ;


      $("#maplinks a").click(function(event){
      event.preventDefault();
                  var markerid = $(event.target).data("markerid");
                  var markers = cluster.markers();

                  $.each(markers,function (){
                    console.warn(this.id);
                    if (this.id == markerid){
                      var lat = this.position.lat();
                      var lon = this.position.lng();
                  
                          var center = new google.maps.LatLng(lat, lon);
                          gmap.panTo(center);
                          gmap.setZoom(6);
                          google.maps.event.trigger(this, 'click', {});
                      ;
                    }
                  });

      });


  });
</script>
<div id="maplinks">
<a href='#' data-lat='36.1128' data-lon='-113.9961' data-markerid="1">Location 1</a>
<a href='#' data-lat='42.4280' data-lon='-110.5885' data-markerid="2">Location 2</a>
<a href='#' data-lat='44.4280' data-lon='60.5985' data-markerid="3">Location 3</a>
<a href='#' data-lat='13.4280' data-lon='44.5895' data-markerid="4">Location 4</a>
<a href='#' data-lat='44.4280' data-lon='-13.5185' data-markerid="5">Location 5</a>
<a href='#' data-lat='44.4280' data-lon='-89.5285' data-markerid="6">Location 6</a>
</div>
  </body>
</html>
```

I called directly google maps methods *panTo* and *setZoom*, and didn't find anything equivalent in gmap3.js. If maintainer @jbdemonte have further suggestion, please feel free.

I no one have further considerations, this can be closed.

**Comment by jbdemonte** [comment]
Hi, sorry guys, I was not available this week-end, 
Yes, I guess I would have done something pretty similar to your code

**Comment by jbdemonte** [comment]
Maybe more like this to get the infowindow over the marker:

    <html>
    <head>
      <meta http-equiv="content-type" content="text/html; charset=utf-8" />
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
      <link type="text/css" rel="stylesheet" href="style.css" />
      <script type="text/javascript" src="../gmap3.js"></script>
    <body>
    <div id="map2" class="gmap3"></div>
    <script>
      $(function () {
        var gmap, infowindow;
    
    
        // create an array of markers
        var markers = [];
    
        $('#maplinks a').each(function () {
          var $this = $(this);
          var htmltxt = $this.html();
          var position = {lat: parseFloat($this.data('lat')), lng: parseFloat($this.data('lon'))};
          var data = {
            position: position,
            id: $this.data('markerid'),
            data: htmltxt
          };
    
          $this.click(function () {
            if (infowindow && data.marker) {
              infowindow.setContent(htmltxt);
              gmap.setZoom(6);
              gmap.panTo(position);
              infowindow.open(gmap, data.marker);
            }
          });
    
          markers.push(data);
        });
    
        // create gmap3:
        $("#map2")
          .gmap3({center: [36.1128,-113.9961], zoom: 4})
          .then(function (_gmap) {
            gmap = _gmap;
          })
          .infowindow({
            content: ''
          })
          .then(function (iw) {
            infowindow = iw;
          })
          .cluster({
            size: 200,
            markers: markers,
            cb: function (markers) {
              if (markers.length > 1) { // 1 marker stay unchanged (because cb returns nothing)
                if (markers.length < 20) {
                  return {
                    content: "<div class='cluster cluster-1'>" + markers.length + "</div>",
                    x: -26,
                    y: -26
                  };
                }
                if (markers.length < 50) {
                  return {
                    content: "<div class='cluster cluster-2'>" + markers.length + "</div>",
                    x: -26,
                    y: -26
                  };
                }
                return {
                  content: "<div class='cluster cluster-3'>" + markers.length + "</div>",
                  x: -33,
                  y: -33
                };
              }
            }
          })
        .then(function (cluster) {
          // complete global markers data with google maps marker
          $.each(cluster.markers(), function (_, marker) {
            $.each(markers, function (_, data) {
              if (data.id === marker.id) {
                data.marker = marker;
              }
            });
          })
        })
        .on('click', function (marker, clusterOverlay, cluster, event) {
          if (marker) {
            infowindow.setContent(marker.data);
            infowindow.open(marker.getMap(), marker);
          }
        });
    
      });
    </script>
    <div id="maplinks">
      <a href='#' data-lat='36.1128' data-lon='-113.9961' data-markerid="1">Location 1</a>
      <a href='#' data-lat='42.4280' data-lon='-110.5885' data-markerid="2">Location 2</a>
      <a href='#' data-lat='44.4280' data-lon='60.5985' data-markerid="3">Location 3</a>
      <a href='#' data-lat='13.4280' data-lon='44.5895' data-markerid="4">Location 4</a>
      <a href='#' data-lat='44.4280' data-lon='-13.5185' data-markerid="5">Location 5</a>
      <a href='#' data-lat='44.4280' data-lon='-89.5285' data-markerid="6">Location 6</a>
    </div>
    </body>
    </html>
