### ISSUE TITLE
Map Clear option is not working

### ISSUE THREAD

**Issue by rajath-ramachandran** [jbdemonte/gmap3#118]
I have tried to clear my route map using gmap3 7.2 with the code like.
  $('.map').gmap3({
        clear: {
          id: "mTagX"
        }
      });

But its not working

**Comment by ghost** [comment]
I have the same problem - I can't figure out how to clear (in this case just my markers) the map.

I've got the following:
```
jQuery('#map')
    .gmap3({
      address: myAddress,
      zoom: 14,
      mapTypeId: google.maps.MapTypeId.HYBRID,
      mapTypeControl: false,
      navigationControl: true,
      scrollwheel: false,
      streetViewControl: false
    })
	.once({
		idle: function(map){
			getMarker(map);
		}
	});
```

... calling a function `getMarker()` to fill the map via AJAX from a database. Now that the map is filled, I want to clear all markers when dragging around or something and show the new markers for this specific area. (show markers is working already)

Q: How can I get all currently visible markers and delete them from the map?

**Comment by jbdemonte** [comment]
clear is a part of v6 version, it's no longer available in v7
to remove anything, use the setMap(null) on the object
