### ISSUE TITLE
Offsetting marker?

### ISSUE THREAD

**Issue by sajjadalis** [jbdemonte/gmap3#122]
Is it possible to offset marker to right side? I have an overlay contact form on the map on left side. While location marker is in center and very close to form. So i want map marker a bit on the right side. How can i achieve that?

http://bit.ly/2ii9F21 --> http://bit.ly/2j9Ec6V

Thanks for this plugin.

**Comment by jbdemonte** [comment]
Use the `panBy` method of the map

**Comment by sajjadalis** [comment]
A stupid question maybe but how should i use panBy method. Is there any demo on website? I can't find panBy method in gmap documentation.

**Comment by jbdemonte** [comment]
Once, you get the map object, juste use `map.panBy(x, y)` where x & y are in pixels
https://developers.google.com/maps/documentation/javascript/reference#Map
