### ISSUE TITLE
Problème avec latlng et évènement

### ISSUE THREAD

**Issue by gtraxx** [jbdemonte/gmap3#124]
Bonjour @jbdemonte , j'ai écris un bout de code pour récupérer la latitude et longitude dans un formulaire.
L’exécution ce fait correctement si j'en code une adresse mais lorsque je change celle-ci, le code n'est pas ré exécuter et ne retourne aucune erreur.
Est-ce un problème de propagation ? comment puis je corriger cela.
```
function updateTimer(ts, func) {
        if (this.timer) clearTimeout(this.timer);
        this.timer = setTimeout(func, ts ? ts : 1000);
    }
function loadMapConfig(){
        var infocontent = $('#adress_map').val() + '<br />' + $('#city_map').val() + ' ' + $('#country_map').val();
        var adr = $('#adress_map').val()+' '+ $('#city_map').val() + ', ' + $('#country_map').val();
        //alert(adr);
        $('#contener-map')
            .gmap3()
            .latlng({
                address: adr
            }).then(function(latlng){
            $("#lat_map").val(latlng.lat());
            $("#lng_map").val(latlng.lng());
        }).catch(function (error) {
            console.error('catched: ' + error);
        });
    }
```
La fonction loadMapConfig est executer comme ci : 
```
if ($("#contener-map").length != 0) {
                $('#adress_map').keypress(function () {
                    updateTimer('', 'MC_plugins_gmap.mapConfig();');
                }).change(function () {
                    updateTimer(100, 'MC_plugins_gmap.mapConfig();');
                });
            }
```
Si je modifie l'adresse il n’exécute pas une deuxième fois la fonction

**Comment by jbdemonte** [comment]
de memoire, si tu appelle gmap3 vide, ca fail, car il attend la conf pour l'afficher
c'est pas naturel dans ce process, tu devrais faire ta resolution d'adresse en "classic google" 
pour le moment, la v7 n'inclus pas de service a appeler de cette facon, et je sais pas quand je pourrai repasser dessus

**Comment by jbdemonte** [comment]
hum, en fait, il instancie bien: https://github.com/jbdemonte/gmap3/blob/master/src/gmap3.js#L775

mais avec un options vide, donc ne lance pas le map (logique) https://github.com/jbdemonte/gmap3/blob/master/src/gmap3.js#L1136

donc a priori, tu devrais pouvoir appeler ton latlng

colle des logs avant tes updateTimer voir s'il y passe, (et en passant, bouh c'est pas beau de faire de l'eval ;) )

**Comment by gtraxx** [comment]
C'est vraiment curieux j'ai fais un test et on dirait que les villes avec une syntaxe un peu particulière ne passe pas bien comme par exemple : sart-lez-spa

```
if ($("#contener-map").length != 0) {
                $('#adress_map').keypress(function () {
                    console.log("keypress ok");
                    updateTimer('', 'MC_plugins_gmap.mapConfig();');
                }).change(function () {
                    console.log("keypress change ok");
                    updateTimer(100, 'MC_plugins_gmap.mapConfig();');
                });
            }

```
Resultat dans firebug en changeant 2 fois l'adresses
```
14
keypress ok
keypress change ok
18
keypress ok
keypress change ok
keypress ok
keypress change ok
4
keypress ok
keypress change ok
```
