### ISSUE TITLE
Google Maps API error: MissingKeyMapError

### ISSUE THREAD

**Issue by nodarik** [jbdemonte/gmap3#125]
I see this error on the site:
Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

i guess it needs api key to be registered on google and then use it, but where to enter api key? is there any procedure?

**Comment by ashppa** [comment]
Same here. 
Just I'm trying a theme with ver 5.
shouldn't it work?
where can I enter the API key?

**Comment by nodarik** [comment]
Let's wait for the developers reply :)

**Comment by gtraxx** [comment]
Hi, in the documentation
http://gmap3.net/configuration.html

**Comment by ashppa** [comment]
Thank you @gtraxx , it looks like it doesn't help me.
I think my problem is different:

It says (by google translate): "Oops! Something went wrong.
This page does not load the Google Maps correctly. See Table JavaScript for technical details."

Should I open a different issue?

**Comment by gtraxx** [comment]
Do you have the URL ?

**Comment by nodarik** [comment]
Thank you, it worked for me
Sorry for bothering for the thing which was defined in the documentation

**Comment by gtraxx** [comment]
Hi, no problem :)
