### ISSUE TITLE
Instance of google map seems to be lost

### ISSUE THREAD

**Issue by Drachenfels** [jbdemonte/gmap3#131]
$('.map')
    .gmap3({
        center: {lat: 50, lng: 0},
        zoom: 13,
        mapTypeId : google.maps.MapTypeId.ROADMAP
    })
    .then(function(gMap) {
        console.log(gMap.getZoom())
    })
    .marker({
        position: {lat: 51, lng: 0},
        icon: 'http://maps.google.com/mapfiles/marker_green.png'
    })
    .then(function(gMap) {
        console.log(gMap.getZoom())
    })

Expected outcome is:

    13
    13

Actally what we got is:

    13
    Uncaught TypeError: gMap.getZoom is not a function

Working example on this page:

https://drachenfels.github.io/gmap3-issue/

Open console to see error.

**Comment by Drachenfels** [comment]
Yet another bug (probably source is the same):

```
var map = $('.map')
.gmap3({
    center: {lat: 50, lng: 0},
    zoom: 13,
    mapTypeId : google.maps.MapTypeId.ROADMAP
})

map.on('tilesloaded', function(obj) {
    console.log('aaa')
})

map.marker({
    position: {lat: 51, lng: 0},
    icon: 'http://maps.google.com/mapfiles/marker_green.png'
})

map.on('tilesloaded', function(obj) {
    console.log('bbb')
})
```

Expected output:
```
 > aaa
 > bbb
```

Actual output:
```
 > aaa
```

**Comment by jbdemonte** [comment]
The "then" function after the marker get a marker in parameter

Have a look on http://gmap3.net/api-chaining.html
