### ISSUE TITLE
Make fullscreen / fullwidth

### ISSUE THREAD

**Issue by kamov** [jbdemonte/gmap3#138]
Following this example here http://jsfiddle.net/paulalexandru/T2F5Z/
the maps is not display.
I need to set height.
Any solutions?

Thanks

**Comment by Xarksass** [comment]
Hello, I don't understand the problem you're encountering. When I follow your link to the jsfiddle, the map is displayed no matter on which browser I open it.

Can you describe exactly what you want to do and what's the problem that appears ?

**Comment by gtraxx** [comment]
Disable Adblock, if it is active :)

**Comment by kamov** [comment]
The jsfiddle don't use gmap3... it's just an example
I fixed this.

Parent div had position: absolute, by changing parent div position to static the problem it's fixed
