### ISSUE TITLE
gmap3 Forum

### ISSUE THREAD

**Issue by dcrobertson01** [jbdemonte/gmap3#141]
Hi,
are the gmap3 forums still being used? I have followed the link from the home page - gmap3.net -> Developer resources -> Forum, which goes to forum.gmap3.net. However, it looks like the css is not being loaded, and the developer tools console shows several javascript files are not being found.

Cheers

DOn

**Comment by atempel** [comment]
The forum seems to have been hijacked... All the posts are in cyrillic and form the same guy.

**Comment by jbdemonte** [comment]
Hi, yes it seems :(
Thanks, I just disable it.
I really don't have time to check for the forum right now, so, hope the user will have the same exchanges on the issue tracker

**Comment by atempel** [comment]
Yeah ): Sad that some solutions were only at forum.
