### ISSUE TITLE
RefererNotAllowedMapError

### ISSUE THREAD

**Issue by rajkumarexe** [jbdemonte/gmap3#143]
Map is running fine when on desktop when saved as a html file but when implemented into the angular4 project, it is not loading and throwing a API error : Missing key on console. On implementing things mentioned in configuration file it should different error RefererNotAllowedMapError,
Am running the project on localhost:8080 is that an issue. Please help me to overcome the issue, and also please let me know is it necessary for me to use the key.

**Comment by jbdemonte** [comment]
I don't know this error, but google it, I guess the stackoverflow issue may help you
https://stackoverflow.com/questions/35288250/google-maps-javascript-api-referernotallowedmaperror?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
