### ISSUE TITLE
markers data 

### ISSUE THREAD

**Issue by butcherfl** [jbdemonte/gmap3#23]
Hi i  need to add multiple markers from my DB
i can do that except data variable (for infowindow)
i use the sample for gmap3.net
where tab is array of lan & lng (i.e tab[0] = 54.55,44.33)
<code>
{ action: 'addMarkers',
                  markers:tab,
              marker:{
                  options:{
                    draggable: false
                  },
                  events:{
                    mouseover: function(marker, event, data){
                      var map = $(this).gmap3('get'),
                          infowindow = $(this).gmap3({action:'get', name:'infowindow'});
                      if (infowindow){
                        infowindow.open(map, marker);
                        infowindow.setContent(data);
                      } else {
                        $(this).gmap3({action:'addinfowindow', anchor:marker, options:{content: data}});
                      }
                    },
                    mouseout: function(){
                      var infowindow = $(this).gmap3({action:'get', name:'infowindow'});
                      if (infowindow){
                        infowindow.close();
                      }
                    }
                  }
                }
              }
</code>
how to modify that table (or add another) to set the info window (i try with lan:xx.xx,lng:xx.xx,data:xxxxx and similiar) 
i have no idea what structure that must be
THX for reply
Janusz Kobylarz

**Comment by adam-jones-net** [comment]
> on http://gmap3.net/forum/

That would be ok if the forum existed still ;)
