### ISSUE TITLE
bug in extendsBounds causes infinite loop in redraw

### ISSUE THREAD

**Issue by wiseman** [jbdemonte/gmap3#64]
I believe there's a bug in `extendsBounds` that can cause an infinite loop during `redraw` if you have a marker near the north pole.

The problem is that if the marker is located within cluster radius pixels of the north pole, `extendsBounds` does not correctly compute the north bounding latitude, which should be 90 degrees.

**Comment by timrross** [comment]
Hi,  think I've been strugling with the same thing for the last couple of days too. I'll see if I can get an example together

**Comment by mnicolas80** [comment]
Hi, I tried to pass coordinates like lat: -90 degrees, lng: 180 degrees on a cluster implementation, but the script crashes.
Then I tried to add only one marker with the similar coordinates, but the issue remains. Any idea about this issue? Thank you.

**Comment by timrross** [comment]
I can reproduce the problem  with the code below. -90 is a legitimate latitude, but it's not possible to display it on a google maps projection. Maybe there should be a filter to stop markers being rendered if they are outside the display area of the map.

```javascript
$(document).ready(function () {
    var test = [{
        latLng: [ -90, 0 ] // South pole!
    }];
    $("#map").gmap3({
        marker:{
            values: test,
            cluster:{
                radius: 100,
                0: {
                    content: "<div class='cluster cluster-1'>CLUSTER_COUNT</div>"
                }
            }
        }
    });
});
```
