### ISSUE TITLE
Show Infowindow on init

### ISSUE THREAD

**Issue by alsahh** [jbdemonte/gmap3#74]
Hey,

is it possible to show the infowindow of a marker on init?

I tried:

```javascript
marker: {
	values: [{
		address: _address,
		data:_data
	}],
	options: {
		draggable: false,
	},
	callback: function(marker){
		
		$(this).gmap3({
			infowindow: {
				anchor: marker,
				options: {
					content: marker.data
				}
			}
		});
		
		var map = $(this).gmap3('get');
		var infowindow = $(this).gmap3({
			get: {
				name: 'infowindow'
			}
		});
		
		infowindow.open(map, marker);
	},
}
```

But all i got was "infowindow is undefined". Thank you for helping me.

**Comment by mnicolas80** [comment]
Hello alsahh,

Have included the relevant js library (infowindow.js)?

**Comment by alsahh** [comment]
I can use the code above for the click event of a marker, so i guess yes all libs are included correctly.
