### ISSUE TITLE
Google map issue with toggle

### ISSUE THREAD

**Issue by krishna19** [jbdemonte/gmap3#77]
I tried to use the google maps in a toggle. Unfortunately it's not working properly. I don't see the map, only a gray background and the google maps frame. Do you have any idea how I can fix this problem? But when i resize the window it works fine. How to solve this issue.
And my toggle code
<pre>
jQuery(function($) {
    $(document).ready(function() {
        $("h3.symple-toggle-trigger").click(function() {
            $(this).toggleClass("active").next().slideToggle("fast");
            return false;
        });
    });
});
</pre>

Thanks

**Comment by jbdemonte** [comment]
you need to call it: .gmap3(
