### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ThomasDK81** [jbdemonte/gmap3#80]
Development looks dead and no posts or simular from the author, for a long time.

**Comment by vschoener** [comment]
Hi,

I don't think the project is dead, but I think @jbdemonte is really busy for others projects and surely in his private life now :)

**Comment by jbdemonte** [comment]
Hi, 
Vincent is right, I'm absolutely busy currently,
I keep an eye on the project comments, but, without having any slot for now to do anything on it.
I hope to be back later (soon?)
