### ISSUE TITLE
Styled maps

### ISSUE THREAD

**Issue by anisval** [jbdemonte/gmap3#86]
It seems like the styling options used by gmap3 are not taking effect in the Google Map. A good example is in the gmap3 website, where the styles are not being applied. 
http://gmap3.net/api-styledmaptype.html

**Comment by jbdemonte** [comment]
yes it works, click on the "Style 1" button in the top left corner.
If you want to active it by code, replace maptypeId value by yours, in the example: "style1"
example:

    <html>    
      <head> 
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
        <link type="text/css" rel="stylesheet" href="style.css" />
        <script type="text/javascript" src="../gmap3.js"></script>
      <body>
    <div id="test" class="gmap3"></div>
    <script>
      $(function () {
        $('#test')
          .gmap3({
            center:[41.850033, -87.650052],
            zoom:12,
            mapTypeId: "style2",  // <-------- HERE
            mapTypeControlOptions: {
              mapTypeIds: [google.maps.MapTypeId.ROADMAP, "style1", "style2"]
            }
          })
          .styledmaptype(
              // styleId (gmap3)
              "style1",
              // styles:Array<MapTypeStyle>
              [{
                featureType: "road.highway",
                elementType: "geometry",
                stylers: [
                  { hue: "#ff0022" },
                  { saturation: 60 },
                  { lightness: -20 }
                ]
              }],
              // options?:StyledMapTypeOptions
              {name: "Style 1"}
          )
          .styledmaptype(
              "style2",
              [
                {
                  featureType: "road.highway",
                  elementType: "geometry",
                  stylers: [
                    { hue: "#ff0022" },
                    { saturation: 60 },
                    { lightness: -20 }
                  ]
                },{
                featureType: "road.arterial",
                elementType: "all",
                stylers: [
                  { hue: "#2200ff" },
                  { lightness: -40 },
                  { visibility: "simplified" },
                  { saturation: 30 }
                ]
              },{
                featureType: "road.local",
                elementType: "all",
                stylers: [
                  { hue: "#f6ff00" },
                  { saturation: 50 },
                  { gamma: 0.7 },
                  { visibility: "simplified" }
                ]
              }
              ],
              {name: "Style 2"}
          )
        ;
      });
    </script>
      </body>
    </html>

**Comment by anisval** [comment]
Yeah, my mistake! Thanks for the clarification!
