### ISSUE TITLE
Change icon of specyfic marker

### ISSUE THREAD

**Issue by pawelbrachaczek** [jbdemonte/gmap3#88]
Hi,

How can I change the icon of a specyfic marker?

I tried like this, but old icon dosn't dissapear:

` $map.gmap3().marker({
				position: [selecledMarker.lat, selecledMarker.lng]
			}).then(function(marker){
				    if(marker.icon == "/assets/img/pin-on.png"){
		                    	marker.setIcon("/assets/img/pin.png");
		                    }
});`

**Comment by jbdemonte** [comment]
did you tried an absolute path?

**Comment by pawelbrachaczek** [comment]
How to do it?

**Comment by jbdemonte** [comment]
marker.setIcon("http://yourdomain.com/.../assets/img/pin.png");

**Comment by pawelbrachaczek** [comment]
New icon is visible, but old icon not dissapar (it's bigger).

**Comment by jbdemonte** [comment]
I never saw this kind of problem with google maps, I guess, you're creating another marker instead of updating one existing.
Can you provide a piece of your code

**Comment by pawelbrachaczek** [comment]
Yes, I probably creates a new marker in the same place.
I fix it like that:

`for(var i=0; i < markersLength; i++){
						    			if($map.gmap3().get(i).icon == "/assets/img/pin-on.png"){
						    				$map.gmap3().get(i).setIcon("/assets/img/pin.png");
						    			}
						    		}`
