### ISSUE TITLE
Getting a list of all starbucks within a certain radius of a specified origin not working

### ISSUE THREAD

**Issue by TheInvoker** [jbdemonte/gmap3#91]
Hi,

I want to get a list of all points of an address, say "Starbucks" within a certain radius, with a specified origin point. I have this
```

  $("#map").gmap3({
    getlatlng:{
      address:  "starbucks",
	  from:{'lat': 43.6532, 'lng': 79.3832},
	  radius:30000,
      callback: function(results){
        alert(results.length);
      }
    }
  });
```

But it doesn't seem to work.

Does anyone know how to do it? I can't find any examples of this on the site http://gmap3.net/ 

Thanks

**Comment by jbdemonte** [comment]
previous version code style
