### ISSUE TITLE
How to remove a specific clusterer?

### ISSUE THREAD

**Issue by TheInvoker** [jbdemonte/gmap3#92]
I set up two clusterer's, one with 1 kind of markers, and another with its own kind of markers. Now how do I remove (not disable, but actually remove it) one of the clusterer's (with all its markers)?

`$('#map').gmap3('clear', 'markers');
`
But it did not work.

**Comment by jbdemonte** [comment]
This kind of code is from a previous version, to hide marker, use their setMap(null)
For now, there is no "clear" feature in v7
