### ISSUE TITLE
Missing documentation for "get" feature.

### ISSUE THREAD

**Issue by berarma** [jbdemonte/gmap3#93]
I was looking for a way to get the _google.maps.Map_ object then I found this comment in a code example for the _infowindow_ function:
```javascript
infowindow.open(this.get(0)); // this.get(0) return the map (see "get" feature)
```
I can't find any documentation for this feature.

**Comment by berarma** [comment]
OK, it's there, in the chaining section, although I was looking for a way to get the _google.maps.Map object from a _gmap3_ object, I think I could do:
```javascript
$( "#map" ).gmap().get( 0 );
```
Right? I guess it's the same as in the context chaining but it wasn't clear for me.

**Comment by jbdemonte** [comment]
Indeed, I forgot these page (which make broken links on http://gmap3.net/api-chaining.html)
I'll do asap

In the interim, yes, get allow to retrieve all the results of each chained "action" by its index

**Comment by berarma** [comment]
Yes, I hadn't noticed the broken links. Thanks!

**Comment by jbdemonte** [comment]
Notice the 7.1 update which accept negative indexes

**Comment by berarma** [comment]
Great, thanks!
