### ISSUE TITLE
Accessing elements from the end of the results list

### ISSUE THREAD

**Issue by berarma** [jbdemonte/gmap3#95]
I'm adding markers with related infowindows to a map in a for loop. I'm using
the code from an [example ](http://gmap3.net/api-infowindow.html)in the API documentation, but in the example the event handler is always added to the first element of the results list.

I'd need to do this inside the loop:

```javascript
// Inside the loop, position and content will change for each iteration
$('.map')
  .gmap3()
  .marker({
    position: position
  })
  .infowindow({
    content: content
  })
  .then(function (infowindow) {
    var map = this.get(0);
    var marker = this.get(-1); // HERE: get the marker from the end of the list
    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  });
```

Right now I'm pushing markers to an array and using that array instead of the results list. I could get the whole list and take the last item myself. Both solutions are enough but they seem a bit off for such a common task compared to how easy everything else is.

I'm proposing this API change as an improvement or please let me know if there's another intended way to do it.

Thanks!

**Comment by jbdemonte** [comment]
http://gmap3.net/api-chaining.html#get

**Comment by berarma** [comment]
Added in version 7.1. So fast! Great!
