### ISSUE TITLE
Add cluser

### ISSUE THREAD

**Issue by pawelbrachaczek** [jbdemonte/gmap3#97]
Hi again,

It is possible to add cluster to all markes on map (not create markers with cluser)?

**Comment by jbdemonte** [comment]
Can you explain what you're looking for,
Maybe you're looking for the cluster.add feature on http://gmap3.net/api-cluster.html
If so, have a look on the example: https://github.com/jbdemonte/gmap3/blob/master/dist/examples/cluster-add.html

**Comment by pawelbrachaczek** [comment]
Yes, add() was just what I was looking for, thank You:)

Another question: Can I add click event to cluster and block click on the map, like stopPropagation()?

**Comment by jbdemonte** [comment]
the event is provided in the function arguments, so you should can
